language: rust
rust:
  - 1.42.0
  # - stable
  # - beta
  # - nightly
script:
  - cargo build --verbose --package h2a
  - cargo test --verbose --package h2a
# jobs:
#   # allow_failures:
#   #   - rust: nightly
#   fast_finish: true
cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

matrix:
  include:
    # Linux release build
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl #OPENSSL_STATIC=yes
      before_script:
        - rustup target add $TARGET
        - rustup component add rustfmt
      script:
        - cargo fmt --package h2a -- --check
        - cargo build --locked --release --target $TARGET --package h2a
      addons:
        apt:
          packages:
          - musl-tools
          - linux-headers-generic

deploy:
  provider: releases
  # token: <encrypted token>
  # file: *
  on:
    tags: true