# dist: xenial
language: rust
rust:
- 1.42.0
# - stable

env:
  matrix:
  - PACKAGE=h2a
  # You could enumerate other packages from workspace ...

matrix:
  include:
    
    # Linux release build
    - env: TARGET=x86_64-unknown-linux-musl #OPENSSL_STATIC=yes
      addons:
        apt:
          packages:
          - musl-tools
          - linux-headers-generic

    # Win64? See: https://github.com/japaric/rust-cross/blob/1573dbba707e588bd2715934670dffc480bc3da2/.travis.yml#L38
    - env: TARGET=x86_64-pc-windows-gnu
      addons:
        apt:
          packages:
          - gcc-mingw-w64

before_script:
  - rustup target add $TARGET
  - rustup component add rustfmt
script:
  - cargo fmt --package $PACKAGE -- --check
  - cargo build --locked --release --target $TARGET --package $PACKAGE

before_deploy:
  - ./ci/prepare_deploy.sh $PACKAGE

deploy:
  provider: releases
  file_glob: true
  file: 
    - $PACKAGE-$TRAVIS_TAG-$TARGET.*
  edge: true
  on: # More: https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on
    # branch: release
    # Only when target is defined explicitly ()
    condition: -z "$TARGET"
    tags: true

cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

branches:
  only:
    # release tags
    - /\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never